query GetUsers {
  users_connection(first: 10) {
    edges {
      cursor
      node {
        id
        email
        avatarUrl: avatar_url
        displayName: display_name
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
  }
}
